"""Initial schema with all tables

Revision ID: 31d369a74c32
Revises: 
Create Date: 2026-02-15 10:50:25.924315

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '31d369a74c32'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('serp_results',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('query', sa.String(length=500), nullable=False),
    sa.Column('language', sa.String(length=10), nullable=False),
    sa.Column('country', sa.String(length=10), nullable=False),
    sa.Column('total_results', sa.Integer(), nullable=True),
    sa.Column('featured_snippet', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('people_also_ask', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('related_searches', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('top_results', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('fetched_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_serp_query_date', 'serp_results', ['query', 'fetched_at'], unique=False)
    op.create_index(op.f('ix_serp_results_query'), 'serp_results', ['query'], unique=False)
    op.create_table('websites',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('repo_url', sa.String(length=500), nullable=True),
    sa.Column('repo_path', sa.String(length=500), nullable=True),
    sa.Column('repo_branch', sa.String(length=100), nullable=True),
    sa.Column('ssh_host', sa.String(length=255), nullable=True),
    sa.Column('ssh_port', sa.Integer(), nullable=True),
    sa.Column('ssh_user', sa.String(length=100), nullable=True),
    sa.Column('ssh_key_path', sa.String(length=500), nullable=True),
    sa.Column('language', sa.String(length=10), nullable=False),
    sa.Column('country', sa.String(length=10), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_websites_domain'), 'websites', ['domain'], unique=True)
    op.create_table('analysis_runs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('website_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', name='analysisstatus'), nullable=False),
    sa.Column('fetcher_type', sa.Enum('HTTPX', 'PLAYWRIGHT', name='fetchertype'), nullable=False),
    sa.Column('urls', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('pages_analyzed', sa.Integer(), nullable=False),
    sa.Column('embedding_provider', sa.String(length=50), nullable=False),
    sa.Column('embedding_model', sa.String(length=100), nullable=False),
    sa.Column('max_keywords', sa.Integer(), nullable=False),
    sa.Column('num_clusters', sa.Integer(), nullable=False),
    sa.Column('total_keywords', sa.Integer(), nullable=False),
    sa.Column('total_clusters', sa.Integer(), nullable=False),
    sa.Column('intent_summary', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['website_id'], ['websites.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_analysis_runs_website_created', 'analysis_runs', ['website_id', 'started_at'], unique=False)
    op.create_index(op.f('ix_analysis_runs_website_id'), 'analysis_runs', ['website_id'], unique=False)
    op.create_table('serp_positions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('website_id', sa.Integer(), nullable=False),
    sa.Column('serp_result_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.Column('url', sa.String(length=1000), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('snippet', sa.Text(), nullable=True),
    sa.Column('is_featured', sa.Boolean(), nullable=False),
    sa.Column('in_top_10', sa.Boolean(), nullable=False),
    sa.Column('in_top_3', sa.Boolean(), nullable=False),
    sa.Column('checked_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['serp_result_id'], ['serp_results.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['website_id'], ['websites.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_positions_serp_position', 'serp_positions', ['serp_result_id', 'position'], unique=False)
    op.create_index('ix_positions_website_date', 'serp_positions', ['website_id', 'checked_at'], unique=False)
    op.create_index(op.f('ix_serp_positions_serp_result_id'), 'serp_positions', ['serp_result_id'], unique=False)
    op.create_index(op.f('ix_serp_positions_website_id'), 'serp_positions', ['website_id'], unique=False)
    op.create_table('keyword_clusters',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('analysis_run_id', sa.Integer(), nullable=False),
    sa.Column('cluster_label', sa.Integer(), nullable=False),
    sa.Column('cluster_name', sa.String(length=500), nullable=True),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('avg_tfidf_score', sa.Float(), nullable=True),
    sa.Column('top_keywords', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('intent_distribution', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('centroid_embedding', postgresql.ARRAY(sa.Float()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['analysis_run_id'], ['analysis_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_clusters_analysis_label', 'keyword_clusters', ['analysis_run_id', 'cluster_label'], unique=False)
    op.create_index(op.f('ix_keyword_clusters_analysis_run_id'), 'keyword_clusters', ['analysis_run_id'], unique=False)
    op.create_table('page_analyses',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('analysis_run_id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=1000), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('word_count', sa.Integer(), nullable=False),
    sa.Column('main_text_length', sa.Integer(), nullable=False),
    sa.Column('keywords_found', sa.Integer(), nullable=False),
    sa.Column('main_content', sa.Text(), nullable=True),
    sa.Column('meta_description', sa.Text(), nullable=True),
    sa.Column('meta_keywords', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('h1_tags', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('h2_tags', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('fetch_success', sa.Boolean(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('analyzed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['analysis_run_id'], ['analysis_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_page_analyses_analysis_run_id'), 'page_analyses', ['analysis_run_id'], unique=False)
    op.create_index(op.f('ix_page_analyses_url'), 'page_analyses', ['url'], unique=False)
    op.create_index('ix_pages_analysis_url', 'page_analyses', ['analysis_run_id', 'url'], unique=False)
    op.create_table('keywords',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('analysis_run_id', sa.Integer(), nullable=False),
    sa.Column('cluster_id', sa.Integer(), nullable=True),
    sa.Column('keyword', sa.String(length=500), nullable=False),
    sa.Column('intent', sa.Enum('INFORMATIONAL', 'COMMERCIAL', 'NAVIGATIONAL', 'TRANSACTIONAL', name='intenttype'), nullable=False),
    sa.Column('tf_idf_score', sa.Float(), nullable=False),
    sa.Column('frequency', sa.Integer(), nullable=False),
    sa.Column('embedding', postgresql.ARRAY(sa.Float()), nullable=True),
    sa.Column('source_urls', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['analysis_run_id'], ['analysis_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['cluster_id'], ['keyword_clusters.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_keywords_analysis_intent', 'keywords', ['analysis_run_id', 'intent'], unique=False)
    op.create_index(op.f('ix_keywords_analysis_run_id'), 'keywords', ['analysis_run_id'], unique=False)
    op.create_index('ix_keywords_analysis_tfidf', 'keywords', ['analysis_run_id', 'tf_idf_score'], unique=False)
    op.create_index(op.f('ix_keywords_keyword'), 'keywords', ['keyword'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_keywords_keyword'), table_name='keywords')
    op.drop_index('ix_keywords_analysis_tfidf', table_name='keywords')
    op.drop_index(op.f('ix_keywords_analysis_run_id'), table_name='keywords')
    op.drop_index('ix_keywords_analysis_intent', table_name='keywords')
    op.drop_table('keywords')
    op.drop_index('ix_pages_analysis_url', table_name='page_analyses')
    op.drop_index(op.f('ix_page_analyses_url'), table_name='page_analyses')
    op.drop_index(op.f('ix_page_analyses_analysis_run_id'), table_name='page_analyses')
    op.drop_table('page_analyses')
    op.drop_index(op.f('ix_keyword_clusters_analysis_run_id'), table_name='keyword_clusters')
    op.drop_index('ix_clusters_analysis_label', table_name='keyword_clusters')
    op.drop_table('keyword_clusters')
    op.drop_index(op.f('ix_serp_positions_website_id'), table_name='serp_positions')
    op.drop_index(op.f('ix_serp_positions_serp_result_id'), table_name='serp_positions')
    op.drop_index('ix_positions_website_date', table_name='serp_positions')
    op.drop_index('ix_positions_serp_position', table_name='serp_positions')
    op.drop_table('serp_positions')
    op.drop_index(op.f('ix_analysis_runs_website_id'), table_name='analysis_runs')
    op.drop_index('ix_analysis_runs_website_created', table_name='analysis_runs')
    op.drop_table('analysis_runs')
    op.drop_index(op.f('ix_websites_domain'), table_name='websites')
    op.drop_table('websites')
    op.drop_index(op.f('ix_serp_results_query'), table_name='serp_results')
    op.drop_index('ix_serp_query_date', table_name='serp_results')
    op.drop_table('serp_results')
    # ### end Alembic commands ###
