"""Configuration for keyword intent detection rules."""

# Transactional intent: user ready to act (buy, download, order, subscribe)
TRANSACTIONAL_PHRASES = [
    "buy",
    "purchase",
    "order",
    "subscribe",
    "sign up",
    "signup",
    "register",
    "checkout",
    "download",
    "get started",
    "start free trial",
    "free trial",
    "book",
    "appoint",
    "price",
    "pricing",
    "cost",
    "sale",
    "discount",
    "coupon",
    "promo",
    "deal",
    "купить",
    "заказать",
    "оформить",
    "скачать",
    "подписаться",
    "регистрация",
    "цена",
    "стоимость",
    "скидка",
    "акция",
    "дешево",
]

# Commercial investigation intent: compare and evaluate
COMMERCIAL_PHRASES = [
    "best",
    "top",
    "vs",
    "versus",
    "compare",
    "comparison",
    "review",
    "ratings",
    "alternatives",
    "which is better",
    "pros and cons",
    "benchmark",
    "обзор",
    "сравнение",
    "лучший",
    "топ",
    "рейтинг",
    "альтернативы",
    "что выбрать",
]

# Navigational intent: locate specific site/page
NAVIGATIONAL_PHRASES = [
    "login",
    "sign in",
    "signin",
    "official",
    "homepage",
    "site",
    "website",
    "docs",
    "documentation",
    "support",
    "contact",
    "github",
    "facebook",
    "instagram",
    "twitter",
    "linkedin",
    "youtube",
    "telegram",
    "профиль",
    "вход",
    "логин",
    "официальный",
    "сайт",
    "документация",
    "поддержка",
    "контакты",
]

# Informational intent: learn or understand
INFORMATIONAL_PHRASES = [
    "what is",
    "what are",
    "how to",
    "how does",
    "why",
    "tutorial",
    "guide",
    "example",
    "examples",
    "symptoms",
    "definition",
    "explain",
    "learn",
    "tips",
    "faq",
    "что такое",
    "как",
    "почему",
    "инструкция",
    "пример",
    "примеры",
    "симптомы",
    "объяснение",
    "как работает",
]
